-- TODO: 실서비스 전에는 Supabase Auth 관리자 권한 필요.
-- TODO: 실서비스 전에는 Supabase Auth 기반으로 통역사 본인 계정만 지원 가능하게 해야 함.
-- 빠른 테스트를 위해 공고 조회/지원/관리자 지원 상태 변경 권한을 anon role에 임시로 엽니다.

alter table public.requests
add column if not exists is_public boolean not null default false;

alter table public.requests
add column if not exists deadline date;

alter table public.requests
add column if not exists required_level text;

alter table public.requests
add column if not exists client_visible_name text;

alter table public.requests
add column if not exists job_description text;

alter table public.requests
add column if not exists dress_code text;

alter table public.requests
add column if not exists interpreter_fee bigint not null default 0;

alter table public.requests
add column if not exists job_field text;

alter table public.requests
add column if not exists required_count integer not null default 1;

update public.requests
set interpreter_fee = coalesce(nullif(interpreter_fee, 0), interpreter_price, interpreter_pay, 0),
    job_description = coalesce(job_description, request_detail),
    required_level = coalesce(required_level, 'Lv1'),
    job_field = coalesce(job_field, '한일 비즈니스 통역');

create table if not exists public.request_applications (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.requests(id) on delete cascade,
  interpreter_id bigint references public.interpreters(id) on delete set null,
  applicant_name text not null,
  applicant_contact text not null,
  kakao_or_line text,
  message text,
  status text not null default 'pending',
  created_at timestamp with time zone not null default now()
);

create unique index if not exists request_applications_request_contact_uidx
on public.request_applications(request_id, applicant_contact);

create unique index if not exists request_applications_request_interpreter_uidx
on public.request_applications(request_id, interpreter_id)
where interpreter_id is not null;

create index if not exists request_applications_request_id_idx
on public.request_applications(request_id);

create index if not exists request_applications_status_idx
on public.request_applications(status);

alter table public.request_applications enable row level security;

drop policy if exists "TEMP public insert applications" on public.request_applications;
create policy "TEMP public insert applications"
on public.request_applications
for insert
to anon
with check (true);

drop policy if exists "TEMP admin read applications" on public.request_applications;
create policy "TEMP admin read applications"
on public.request_applications
for select
to anon
using (true);

drop policy if exists "TEMP admin update applications" on public.request_applications;
create policy "TEMP admin update applications"
on public.request_applications
for update
to anon
using (true)
with check (true);
