-- TODO: 실서비스 전에는 Supabase Auth 관리자 권한 필요.
-- 빠른 테스트를 위해 anon role에 관리자 화면용 조회/수정 권한을 임시로 열어둡니다.

alter table public.interpreters
add column if not exists approved boolean not null default false;

alter table public.interpreters
add column if not exists warning_count integer not null default 0;

alter table public.interpreters
add column if not exists level text not null default 'Lv1';

alter table public.interpreters
alter column status set default 'active';

update public.interpreters
set status = 'active'
where status is null or status in ('approved', 'pending');

update public.interpreters
set level = 'Lv1'
where level is null or level = '';

alter table public.requests
add column if not exists contact_status text not null default 'not_contacted';

alter table public.requests
add column if not exists client_price bigint not null default 0;

alter table public.requests
add column if not exists interpreter_price bigint not null default 0;

alter table public.requests
add column if not exists profit bigint not null default 0;

alter table public.requests
add column if not exists payment_status text not null default 'unpaid';

alter table public.requests
alter column status set default 'pending';

update public.requests
set status = coalesce(status, 'pending'),
    contact_status = coalesce(contact_status, 'not_contacted'),
    client_price = case
      when client_price = 0 then coalesce(estimated_price, 0)
      else client_price
    end,
    interpreter_price = case
      when interpreter_price = 0 then coalesce(interpreter_pay, 0)
      else interpreter_price
    end,
    payment_status = coalesce(payment_status, 'unpaid');

update public.requests
set profit = coalesce(client_price, 0) - coalesce(interpreter_price, 0);

create table if not exists public.request_interpreters (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.requests(id) on delete cascade,
  interpreter_id bigint not null references public.interpreters(id) on delete cascade,
  assigned_at timestamp with time zone not null default now(),
  unique (request_id, interpreter_id)
);

create index if not exists request_interpreters_request_id_idx
on public.request_interpreters(request_id);

create index if not exists request_interpreters_interpreter_id_idx
on public.request_interpreters(interpreter_id);

alter table public.request_interpreters enable row level security;

drop policy if exists "TEMP admin read request interpreters" on public.request_interpreters;
create policy "TEMP admin read request interpreters"
on public.request_interpreters
for select
to anon
using (true);

drop policy if exists "TEMP admin insert request interpreters" on public.request_interpreters;
create policy "TEMP admin insert request interpreters"
on public.request_interpreters
for insert
to anon
with check (true);

drop policy if exists "TEMP admin delete request interpreters" on public.request_interpreters;
create policy "TEMP admin delete request interpreters"
on public.request_interpreters
for delete
to anon
using (true);

drop policy if exists "TEMP admin update requests" on public.requests;
create policy "TEMP admin update requests"
on public.requests
for update
to anon
using (true)
with check (true);
